# This file used by make for docker-composer container operations
# including docker image build

version: '2.1'

services:

  app:
    image: ${DC_IMAGE:-lekovr/fiwes}
    command:
      --html --http_addr :8080
    ports:
      - "${SERVER_PORT:-8080}:8080"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIR:-./var/data}:/data
    build:
      context: .
      args:
        - GO_VERSION=${GO_VERSION:-1.12.4}
