version: '2.0'

services:

  app:
    image: ${DC_IMAGE}
    command:
      --html --http_addr :8080
    ports:
      - "${SERVER_PORT}:8080"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIR}:/data
    build:
      context: .
      args:
        - GO_VERSION
